apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustom-sample-app
spec: 
  template:
    spec:
      containers:
      - name: nginx
        volumeMounts:
        - name: nginx-html-mount
          mountPath: /usr/share/nginx/html  
      volumes:
      - name: nginx-html-mount
        configMap:
          name: nginx-html