apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- envs:
  - config.properties
  name: kustom-sample-app-config
resources:
- ../../base
patches:
- path: replicas.yaml
