apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustom-sample-app
    spec:
      containers:
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: index.html
            path: index.html