apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustom-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustom-sample-app  
  template:
    spec:
      containers:
      - name: nginx
        image: openresty/openresty:alpine
        ports:
        - containerPort: 80   
        envFrom:
        - configMapRef:
            name: kustom-sample-app-config 
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf                     
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "16Mi"
            cpu: "50m"
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config            