apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustom-sample-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: kustom-sample-app-config
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "16Mi"
            cpu: "50m"