apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-kustomize
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "16Mi"
            cpu: "50m"