resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: kustom-sample-app

commonAnnotations:
  app: kustom-sample-app-annontations

namePrefix:
  jmiller-

nameSuffix:
  -v1

configMapGenerator:
- name: nginx-config
  env: nginx.conf